-- MySQL Script generated by MySQL Workbench
-- Fri Mar  3 20:13:20 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_app_notas` DEFAULT CHARACTER SET utf8 ;
USE `db_app_notas` ;

-- -----------------------------------------------------
-- Table `db_app_notas`.`Usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_app_notas`.`Usuarios` (
  `idUsuario` INT NOT NULL,
  `nombre_usuario` VARCHAR(45) NOT NULL,
  `correo` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idUsuario`, `nombre_usuario`, `correo`, `password`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_app_notas`.`Categorias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_app_notas`.`Categorias` (
  `idCategoria` INT NOT NULL,
  `Descripcion` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idCategoria`, `Descripcion`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_app_notas`.`Prioridades`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_app_notas`.`Prioridades` (
  `idPrioridad` INT NOT NULL,
  `Descripcion` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idPrioridad`, `Descripcion`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_app_notas`.`Notas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_app_notas`.`Notas` (
  `idNota` INT NOT NULL,
  `Titulo` VARCHAR(45) NOT NULL,
  `Contenido` LONGTEXT NOT NULL,
  `FechaCreacion` DATETIME NOT NULL,
  `FechaModificacion` DATETIME NOT NULL,
  `Categorias_idCategoria` INT NOT NULL,
  `FechaLimite` DATE NOT NULL,
  `Prioridades_idPrioridad` INT NOT NULL,
  `Finalizado` BIT NOT NULL,
  PRIMARY KEY (`idNota`),
  INDEX `fk_Notas_Categorias1_idx` (`Categorias_idCategoria` ASC),
  INDEX `fk_Notas_Prioridades1_idx` (`Prioridades_idPrioridad` ASC),
  CONSTRAINT `fk_Notas_Categorias1`
    FOREIGN KEY (`Categorias_idCategoria`)
    REFERENCES `mydb`.`Categorias` (`idCategoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Notas_Prioridades1`
    FOREIGN KEY (`Prioridades_idPrioridad`)
    REFERENCES `mydb`.`Prioridades` (`idPrioridad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_app_notas`.`Recordatorios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_app_notas`.`Recordatorios` (
  `idRecordatorio` INT NOT NULL,
  `Fecha` DATE NOT NULL,
  `Hora` TIME NOT NULL,
  `Notas_idNota` INT NOT NULL,
  PRIMARY KEY (`idRecordatorio`, `Fecha`, `Hora`, `Notas_idNota`),
  INDEX `fk_Recordatorios_Notas1_idx` (`Notas_idNota` ASC),
  CONSTRAINT `fk_Recordatorios_Notas1`
    FOREIGN KEY (`Notas_idNota`)
    REFERENCES `mydb`.`Notas` (`idNota`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_app_notas`.`Usuarios_Notas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_app_notas`.`Usuarios_Notas` (
  `idUsuarios_Notas` INT NOT NULL,
  `Notas_idNota` INT NOT NULL,
  `Usuarios_idUsuario` INT NOT NULL,
  PRIMARY KEY (`idUsuarios_Notas`, `Notas_idNota`, `Usuarios_idUsuario`),
  INDEX `fk_Usuarios_Notas_Notas1_idx` (`Notas_idNota` ASC),
  INDEX `fk_Usuarios_Notas_Usuarios1_idx` (`Usuarios_idUsuario` ASC),
  CONSTRAINT `fk_Usuarios_Notas_Notas1`
    FOREIGN KEY (`Notas_idNota`)
    REFERENCES `mydb`.`Notas` (`idNota`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Usuarios_Notas_Usuarios1`
    FOREIGN KEY (`Usuarios_idUsuario`)
    REFERENCES `mydb`.`Usuarios` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
